---
title: "Knowledge Mining (EPPS 6323)"
subtitle: "Assignment 8"
author: "Guan Chen"
date: last-modified
toc: false
title-block-banner: true
---

```{R}
require(ISLR)
require(MASS)
require(descr)
attach(Smarket)

## Linear Discriminant Analysis
freq(Direction)
train = Year<2005
lda.fit=lda(Direction~Lag1+Lag2,data=Smarket, subset=Year<2005)
lda.fit
plot(lda.fit, col="dodgerblue")
Smarket.2005=subset(Smarket,Year==2005) # Creating subset with 2005 data for prediction
lda.pred=predict(lda.fit,Smarket.2005)
names(lda.pred)
lda.class=lda.pred$class
Direction.2005=Smarket$Direction[!train] 
table(lda.class,Direction.2005) 
data.frame(lda.pred)[1:5,]
table(lda.pred$class,Smarket.2005$Direction)
mean(lda.pred$class==Smarket.2005$Direction)


```

The best subset selection model will have the smallest training rss.
The stepwise selection models will have the smallest test rss. Between the forward and backward models, it will depend on the specific data being modeled. 

```{R}
set.seed(123)
x <- rnorm(100)
eps <- rnorm(100)

y <- 4 + 9 * x + 2 * x^2 + x^3 + eps

plot(x)
plot(y)

require(leaps)

best_subset <- regsubsets(y ~ poly(x, 10, raw = T), data = data.frame(y,x, nvmax = 10))
bic <- summary(best_subset)$bic
cp <- summary(best_subset)$cp
adjr2 <- summary(best_subset)$adjr2

plot(bic, type = "b", pch = 16, col = "blue", 
     xlab = "Model Number", ylab = "BIC Value", 
     main = "BIC Values for Different Models")
plot(cp, type = "b", pch = 16, col = "blue", 
     xlab = "Model Number", ylab = "Cp Value", 
     main = "Cp Values for Different Models")
plot(adjr2, type = "b", pch = 16, col = "blue", 
     xlab = "Model Number", ylab = "Adjusted R^2 Value", 
     main = "Adjusted R^2 Values for Different Models")

which.min(bic)
which.min(cp)
which.max(adjr2)

coef(best_subset, id = 3)
```
The best model is model 3 which has the lowest BIC value and Cp value. While model 7 has the maximum adjusted R squared value, the R squared plot begins to plateau at model 3, and I suspect overfitting to occur. 

The coefficients for model 3 are 3.97, 8.92, 1.91, and 1.02 for the intercept, B1, B2, and B3 respectively.

```{R}
for_subset <- regsubsets(y ~ poly(x, 10, raw = T), data = data.frame(y,x, nvmax = 10), method = "forward")

plot(summary(for_subset)$bic, type = "b", pch = 16, col = "blue", 
     xlab = "Model Number", ylab = "BIC Value", 
     main = "BIC Values for Different Models")
plot(summary(for_subset)$cp, type = "b", pch = 16, col = "blue", 
     xlab = "Model Number", ylab = "Cp Value", 
     main = "Cp Values for Different Models")
plot(summary(for_subset)$adjr2, type = "b", pch = 16, col = "blue", 
     xlab = "Model Number", ylab = "Adjusted R^2 Value", 
     main = "Adjusted R^2 Values for Different Models")

which.min(summary(for_subset)$bic)
which.min(summary(for_subset)$cp)
which.max(summary(for_subset)$adjr2)


coef(for_subset, id = 3)
```

The best model is model 3 again with the lowest BIC and Cp values. Model 4 wins the best adjusted R squared value but model 3 has a similar adjusted R squared value according to the plot. 

The coefficients for model 3 are 3.97, 8.92, 1.91, and 1.02 for the intercept, B1, B2, and B3 respectively. 



```{R}
bac_subset <- regsubsets(y ~ poly(x, 10, raw = T), data = data.frame(y,x, nvmax = 10), method = "backward")

plot(summary(bac_subset)$bic, type = "b", pch = 16, col = "blue", 
     xlab = "Model Number", ylab = "BIC Value", 
     main = "BIC Values for Different Models")
plot(summary(bac_subset)$cp, type = "b", pch = 16, col = "blue", 
     xlab = "Model Number", ylab = "Cp Value", 
     main = "Cp Values for Different Models")
plot(summary(bac_subset)$adjr2, type = "b", pch = 16, col = "blue", 
     xlab = "Model Number", ylab = "Adjusted R^2 Value", 
     main = "Adjusted R^2 Values for Different Models")

which.min(summary(bac_subset)$bic)
which.min(summary(bac_subset)$cp)
which.max(summary(bac_subset)$adjr2)

coef(bac_subset, id = 3)
```

Using the backwards stepwise selection method, model 4 performs the best on all 3 metrics. The coefficients are 3.96, 9.89, 1.97, and 0.17 for the intercept, B1, B2, and B3 respectively. 

