---
title: "Knowledge Mining (EPPS 6323)"
subtitle: "Assignment 7"
author: "Guan Chen"
date: last-modified
toc: false
title-block-banner: true
---

```{R}
require(ISLR)

# Check dataset Smarket
?Smarket
names(Smarket)
summary(Smarket)

# Create a dataframe for data browsing
sm=Smarket

# Bivariate Plot of inter-lag correlations
pairs(Smarket,col=Smarket$Direction,cex=.5, pch=20)

# Logistic regression
glm.fit=glm(Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume,
            data=Smarket,family=binomial)
summary(glm.fit)
glm.probs=predict(glm.fit,type="response") 
glm.probs[1:5]
glm.pred=ifelse(glm.probs>0.5,"Up","Down")
attach(Smarket)
table(glm.pred,Direction)
mean(glm.pred==Direction)

# Make training and test set for prediction
train = Year<2005
glm.fit=glm(Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume,
            data=Smarket,family=binomial, subset=train)
glm.probs=predict(glm.fit,newdata=Smarket[!train,],type="response") 
glm.pred=ifelse(glm.probs >0.5,"Up","Down")
Direction.2005=Smarket$Direction[!train]
table(glm.pred,Direction.2005)
mean(glm.pred==Direction.2005)
#Fit smaller model
glm.fit=glm(Direction~Lag1+Lag2,
            data=Smarket,family=binomial, subset=train)
glm.probs=predict(glm.fit,newdata=Smarket[!train,],type="response") 
glm.pred=ifelse(glm.probs >0.5,"Up","Down")
table(glm.pred,Direction.2005)
mean(glm.pred==Direction.2005)

# Check accuracy rate
106/(76+106)

# Can you interpret the results?

```

2a: Predictor variables are normally distributed, each predictor variable has the same variance, and the response variable must be categorical as LDA is used for classification problems.

2b: LDA is used for multiclass classification whereas logistic regression is for binary classification. LDA also makes assumptions about the distribution of the data whereas logistic regression does not.

2c: The receiving operator characteristic (ROC) evaluates the performance of a classifier model.

2d: Sensitivity is the true positive rate. Specificity is the true negative rate. Generally, sensitivity is more important since there tends to be immediate and severe consequences for false positives (i.e. an innocent person who's found guilty will go to jail) rather than false negatives. Neither type I or II errors are desirable, but high sensitivity should be prioritized. 

2e: Sensitivity is more important for prediction based on the chart.

3: 
```{R}
prediction_error <- (252+23)/10000
cat("Prediction error:", formatC(prediction_error * 100, format = "f", digits = 2), "%\n")
```

