---
title: "Knowledge Mining (EPPS 6323)"
subtitle: "Assignment 1"
author: "Guan Chen"
date: last-modified
toc: false
title-block-banner: true
---

### Review of "To explain or to predict" by Galit Shmueli and "Statistical modeling: The two cultures" by Leo Breiman

Both papers talk about the same topic: the distinction between predictive and explanatory modeling. The authors would likely concur in that there is merit in either modeling technique depending on the circumstances. However, the authors adopt contrasting attitudes towards the use-cases for each modeling technique.

Leo Breiman is a passionate advocate for predictive modeling, frequently citing its superiority in predictive accuracy as compared to more traditional statistical modeling methods. Furthermore, he criticizes statisticians for routinely attempting to employ explanatory modeling in situations where predictive modeling may perform better. Conversely, Galit Shmueli presents a more neutral tone and goes into deep detail regarding the different applications and advantages for each modeling technique respectively.

These differences in attitudes toward modeling techniques may be attributed to the differences in the authors background and experiences. Breiman has experience working in the industry whereas Shmueli has been dedicated to academia. Perhaps these attitudes are reflective of preferences within the environments they have worked in. I would hypothesize that predictive modeling yields more immediately actionable data which would benefit companies trying to make data driven choices while explanatory modeling is more conducive to making broad conclusions and associations. Ultimately, these modeling techniques have their respective advantages and disadvantages and statisticians should strive to employ them in the optimal conditions.
