---
title: "Knowledge Mining (EPPS 6323)"
subtitle: "Assignment 2"
author: "Guan Chen"
date: last-modified
toc: false
title-block-banner: true
---

```{r}
library(haven)
library(tidyverse)
TEDS_2016 <- read_stata("https://github.com/datageneration/home/blob/master/DataProgramming/data/TEDS_2016.dta?raw=true")

#Tondu vs Unification
ggplot(TEDS_2016, aes(Tondu)) +
  geom_bar(aes(weight = Unification)) +
  labs(x = "Tondu", y = "Unification")

```

At first glance, it is difficult to identify trends because a lot of the variables are binary (i.e. sex, party, whitecollar).

Missing values can be handled by omitting the NA values.

```{r}
#Tondu vs female
ggplot(TEDS_2016, aes(female)) +
  geom_bar(width = 0.5, aes(weight = Tondu)) +
  labs(x = "Sex", y = "Tondu") 

#Tondu vs DPP
ggplot(TEDS_2016, aes(DPP)) +
  geom_bar(width = 0.5, aes(weight = Tondu)) +
  labs(x = "DPP", y = "Tondu")

#Tondu vs age
ggplot(TEDS_2016, aes(age)) +
  geom_bar(aes(weight = Tondu)) +
  labs(x = "Age", y = "Tondu")

#Tondu vs income
ggplot(TEDS_2016, aes(income)) +
  geom_bar(aes(weight = Tondu)) +
  labs(x = "Income", y = "Tondu")

#Tondu vs edu
ggplot(TEDS_2016, aes(edu)) +
  geom_bar(aes(weight = Tondu)) +
  labs(x = "Education", y = "Tondu")

#Tondu vs Taiwanese
ggplot(TEDS_2016, aes(Taiwanese)) +
  geom_bar(width = 0.5, aes(weight = Tondu)) +
  labs(x = "Taiwanese", y = "Tondu")

#Tondu vs Econ_worse
ggplot(TEDS_2016, aes(Econ_worse)) +
  geom_bar(width = 0.5, aes(weight = Tondu)) +
  labs(x = "Worse Economy", y = "Tondu")

#Tondu vs votetsai
ggplot(TEDS_2016, aes(votetsai)) +
  geom_bar(width = 0.5, aes(weight = Tondu)) +
  labs(x = "Vote Tsai", y = "Tondu")

table(TEDS_2016$Tondu)

TEDS_2016$Tondu<-as.numeric(TEDS_2016$Tondu,labels=c("Unification now”,
“Status quo, unif. in future”, “Status quo, decide later", "Status quo
forever", "Status quo, indep. in future", "Independence now”, “No response"))

#Tondu Frequency
ggplot(TEDS_2016, aes(Tondu)) +
  geom_bar() +
  scale_x_continuous(breaks=c(0:10)) +
  labs(y = "Frequency")

#install.packages("descr")
#descr::freq(TEDS_2016$Tondu)
```
